# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gambhircode
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  enviroment: 
   DEBUG: ${env:DEBUT, 0}
   STAGE: ${env:STAGE, "prod"}
  iam: 
   role: 
    name: serverless-ssm-role
    statements:
      - Effect: 'Allow'
        Resource: '*'
        Action: 
         - 'ssm:GetParameter'
         - 'ssm:GetParameters'
         - 'ssm:GetParameterByPath'
         - 'ssm:GetParameterHistory'
         - 'ssm:DescribeParameters'


functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

custom: 
  dotenv:
    exclude: 
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - DATABASE_URL

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
